name: THEM
favicon: null
layout_spectrum: 0.57767
typography_spectrum: 0.52867
title: M+K
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
