name: THEM
favicon: null
layout_spectrum: 0.8230283695738763
typography_spectrum: 0.52867
title: M+K
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4375
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0
purpose: []
